<?= $renderer->extend('modules/shared/core/views/layout') ?>

<?= $renderer->section('content') ?>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-success">
                <div class="box-header">
                    <a href="<?= route_to('kartu.generate') ?>" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i>&nbsp;&nbsp;Buat Kartu</a>
                    <?= $renderer->include('modules/shared/core/views/notification') ?>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="dataTables_wrapper form-inline dt-bootstrap">
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="data-kartu" class="table table-bordered table-striped dataTable" role="grid">
                                    <thead>
                                        <tr role="row">
                                            <th>#</th>
                                            <th>ID Kartu</th>
                                            <th>Nama</th>
                                            <th>Generated By</th>
                                            <th>Valid Until</th>
                                            <th>Expired In</th>
                                            <th>Created At</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal-show-image">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span></button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <img class="center-block img-responsive front" src="#" alt="">
                    <img class="center-block img-responsive back" src="#" alt="">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
</section>
<?= $renderer->endSection() ?>

<?= $renderer->section('custom-js') ?>
<script src="<?= site_url('adminlte2/bower_components/datatables.net/js/jquery.dataTables.min.js') ?>"></script>
<script src="<?= site_url('adminlte2/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') ?>"></script>
<script>
    $(function() {
        $('#data-kartu').DataTable({
            dom: 'lrtip',
            searching: true,
            responsive: true,
            pageLength: 10,
            processing: true,
            serverSide: true,
            order: [],
            ajax: function(data, callback, settings) {
                var data = {
                    ...data,
                    ['<?= csrf_token() ?>']: '<?= csrf_hash() ?>'
                }
                $.ajax({
                    type: 'post',
                    url: '<?= route_to('api.card.get-data') ?>',
                    data: data,
                    beforeSend: function(xhr) {
                        xhr.setRequestHeader('Authorization', 'Basic ' + btoa('sitaninkadmin:admin123'));
                    },
                    success: function(res) {
                        console.log(res);
                        callback(res);
                    },
                    error: function(err) {
                        console.log(err);
                        callback([]);
                    }
                });
            },
            columns: [{
                    targets: 0,
                    orderable: false,
                    searchable: false
                },
                {
                    targets: 1,
                    orderable: true,
                    searchable: true
                },
                {
                    targets: 2,
                    orderable: true,
                    searchable: true
                },
                {
                    targets: 3,
                    orderable: true,
                    searchable: true
                },
                {
                    targets: 4,
                    orderable: false,
                    searchable: false
                },
                {
                    targets: 5,
                    orderable: false,
                    searchable: false
                },
                {
                    targets: 6,
                    orderable: false,
                    searchable: false
                },
                {
                    targets: 7,
                    orderable: false,
                    searchable: false
                },
            ],
            drawCallback: function(settings) {}
        });

        $('#data-kartu tbody').on('click', 'button.btn.btn-primary', function(e) {
            var idCard = $(this).data().cardId;
            var pekerjaName = $(this).data().pekerjaName;

            fetch(`<?= site_url('api/v1/card') ?>/${idCard}/print`, {
                    method: 'POST',
                    headers: new Headers({
                        'Authorization': 'Basic ' + btoa('sitaninkadmin:admin123')
                    })
                })
                .then((result) => {
                    if (result.status != 200) {
                        throw new Error('Bad server response');
                    }
                    return result.blob();
                })
                .then((data) => {
                    console.log(data);
                    var url = window.URL.createObjectURL(data);
                    var anchor = document.createElement('a');
                    anchor.href = url;
                    anchor.download = Date.now() + '_' + pekerjaName + '.pdf';
                    anchor.click();
                    anchor.remove();
                    window.URL.revokeObjectURL(url);
                })
                .catch((error) => {
                    console.log(error);
                    alert('download error');
                });

            // $.ajax({
            //     type: 'post',
            //     url: `<?= site_url('api/v1/card') ?>/${idCard}/print`,
            //     beforeSend: function(xhr) {
            //         xhr.setRequestHeader('Authorization', 'Basic ' + btoa('sitaninkadmin:admin123'));
            //     },
            //     // xhr: function() {
            //     //     var xhr = new XMLHttpRequest();
            //     //     xhr.onreadystatechange = function() {
            //     //         if (xhr.readyState == 2) {
            //     //             if (xhr.status === 200) {
            //     //                 xhr.responseType = 'blob';
            //     //             } else {
            //     //                 xhr.responseType = 'text';
            //     //             }
            //     //         }
            //     //     }
            //     //     return xhr;
            //     // },
            //     xhrFields: {
            //         responseType: 'blob'
            //     },
            //     success: function(data) {
            //         // var blob = new Blob([data], { type: "application/octetstream" });

            //         // var isIE = false || !!document.documentMode;
            //         // if (isIE) {
            //         //     window.navigator.msSaveBlob(blob, Date.now() + '_' + pekerjaName + '.pdf');
            //         // } else {
            //         //     var url = window.URL || window.webkitURL;
            //         //     link = url.createObjectURL(blob);
            //         //     var a = $('<a>');
            //         //     a.attr('id', 'card-download');
            //         //     a.attr('download', Date.now() + '_' + pekerjaName + '.pdf');
            //         //     a.attr('href', link);
            //         //     $('body').append('a');
            //         //     a[0].click();
            //         //     $('body').find('a#card-download')
            //         //         .remove();
            //         //     url.revokeObjectURL(link);
            //         // }
            //         var a = document.createElement('a');
            //         var url = window.URL.createObjectURL(blob);
            //         a.href = url;
            //         a.download = 'myfile.pdf';
            //         document.body.append(a);
            //         a.click();
            //         a.remove();
            //         window.URL.revokeObjectURL(url);
            //     },
            //     error: function(err) {
            //         console.log(err);
            //     }
            // });
        });

        $('#modal-show-image').on('show.bs.modal', function(e) {
            var relatedTarget = $(e.relatedTarget).data();
            var idBerkas = relatedTarget.idBerkas;

            console.log(idBerkas);
            var $thisElement = $(this);

            $.ajax({
                type: 'get',
                url: `<?= site_url('api/v1/card/get-berkas') ?>/${idBerkas}`,
                beforeSend: function(xhr) {
                    xhr.setRequestHeader('Authorization', 'Basic ' + btoa('sitaninkadmin:admin123'));
                },
                success: function(res) {
                    console.log(res);

                    if (res.data) {
                        $thisElement.find('img.front')
                            .attr('src', `<?= site_url('kartu') ?>/${res.data.filename}`)
                            .attr('alt', 'Front Card');
                        $thisElement.find('img.back')
                            .attr('src', `<?= site_url('kartu') ?>/back-card.png`)
                            .attr('alt', 'Back Card');
                    } else {
                        alert('Failed to show image!');
                    }
                },
                error: function(err) {
                    console.log(err);

                    alert('Failed to show image!');
                }
            });
        });

        // delete card
        $('#data-kartu tbody').on('click', 'tr td button.btn.btn-danger', function(e) {
            var cardId = $(this).data().cardId;

            if (confirm('Anda yakin mau dihapus?')) {
                $.ajax({
                    url: `<?=site_url('kartu2')?>/${cardId}/delete`,
                    type: 'post',
                    data: {
                        ['<?= csrf_token() ?>']: '<?= csrf_hash() ?>'
                    },
                    success: function(res, textStatus, xhr) {
                        console.log(res);

                        alert(res.message);
                        location.reload();
                    },
                    error: function(err) {
                        console.log(err);

                        alert('Something went wrong!');
                    }
                });
            }
        });
    });
</script>
<?= $renderer->endSection() ?>

<?= $renderer->section('custom-css') ?>
<link rel="stylesheet" href="<?= site_url('adminlte2/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') ?>">
<?= $renderer->endSection() ?>